FROM phusion/baseimage:0.9.11
MAINTAINER digitalman2112 <ian.cole@gmail.com>
ENV DEBIAN_FRONTEND noninteractive

# Set correct environment variables
ENV HOME /root

# Use baseimage-docker's init system
CMD ["/sbin/my_init"]

RUN add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe multiverse"
RUN add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe multiverse"

# Install Dependencies
RUN apt-get update -qq && \ 
	apt-get install -qq --force-yes libcairo2-dev libpango1.0-dev libtokyocabinet-dev wget unzip dh-autoreconf && \ 
	apt-get autoremove && \
	apt-get autoclean

# Install duc
RUN wget -P /tmp/ https://github.com/zevv/duc/archive/master.zip
RUN unzip /tmp/master.zip -d /tmp/
RUN cd /tmp/duc-master/ && \
	autoreconf --install && \
	./configure && \
	make && \
	make install && \
	ldconfig
	
#RUN duc

#VOLUME /data

